### ISSUE TITLE
libwrapper conflicts

### ISSUE THREAD

**Issue by jasonckramer** [ruipin/fvtt-lib-wrapper#31]
Hello,

I have started to see a number of errors pop-up in connection with libwrapper. Below is the Conflicts information. Let me know if additional information will assist. Thank you!

[https://screenrec.com/share/WKvHRuFejs](url)

**Comment by ruipin** [comment]
This is not indicative of an issue with libWrapper, but that libWrapper is detecting (potential) conflicts between the modules in that list.

If module features that you want to use do not work, you'll want to report these to the developers of those modules. The #module-troubleshooting channel in the Foundry Discord can also help.

If every module feature you rely on works, you can just disable the libWrapper warnings in the settings.

Closing due to being unrelated to libWrapper.
