### ISSUE TITLE
The Settings Application is Unable to Handle "improper" Wrappers.

### ISSUE THREAD

**Issue by Varriount** [ruipin/fvtt-lib-wrapper#56]
This is a bug in libWrapper, as it prevents libWrapper's "Settings" menu from appearing.

**Describe the bug**
If a package attempts to wrap a (previously libWrap'd) function *without* using libWrapper, libWrapper will attempt to automatically wrap the function anyway, assigning it the package ID of `«unknown»`. While this kind of function is registered, attempting to open libWrapper's settings fails. The settings logic throws the following stack trace:
```
22:46:54.990 Uncaught (in promise) TypeError: can't assign to property "message" on "libWrapper: Invalid package ID '\xABunknown\xBB'": not an object
[Detected 2 packages: settings-extender, lib-wrapper]
    render foundry.js:2012
    promise callback*render foundry.js:2011
    _onClickSubmenu foundry.js:31552
    jQuery 9
    activateListeners foundry.js:31536
    activateListeners settings-extender.js:404
    _render foundry.js:2077
    call_wrapped libWrapper-wrapper.js:467
    <anonymous> listeners.js:111
    _render#0 libWrapper-wrapper.js:162
    _render foundry.js:2736
    render foundry.js:2011
    _onSettingsButton foundry.js:34974
    jQuery 2
        dispatch
        handle
```

(`\xAA` and `\xAB` are the double-arrow marks)

**To Reproduce**
1. Install libWrapper.
2. Correctly wrap a function with libWrapper.
3. *In*correctly wrap the same function.
4. Attempt to open libWrapper's settings.

**Expected behavior**
libWrapper's settings application opens.

**Screenshots**

**Technical Details (please complete the following information):**
 - LibWrapper Version: 1.10.7.0
 - FoundryVTT Version: 0.8.9
 - Browser & Version: Firefox 93

**Comment by ruipin** [comment]
Thanks for the report! I have pushed a fix in version [1.10.8.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.10.8.0).

This issue was actually more in depth than the report. There were 3 bugs here:
1. In certain situations, the error message of `libWrapper.register` would not rely on the package ID provided by the caller when auto-detection failed,
2. The handling of "unknown" packages (i.e. those that fail auto-detection) was broken in the refactoring done for v10.
3. Foundry VTT 0.8.x does not like it when exceptions are thrown as a string, rather than as an error object (which is why the stack trace above is inside `foundry.js`).

v1.10.8.0 fixes all of these, and does some other code refactoring to improve maintainability and try and avoid similar issues in the future.

With these fixes, the settings dialog now opens as expected, even when doing non-libWrapper wrapping.

I'm closing this now, but feel free to re-open if you notice any remaining issues.
