### ISSUE TITLE
[Request] Reduce logging verbosity

### ISSUE THREAD

**Issue by dmrickey** [ruipin/fvtt-lib-wrapper#62]
It would be nice if the `libWrapper: Registered a wrapper` log messages could be suppressed somehow.

**Comment by ruipin** [comment]
Just to get a better idea of the reasons for the request, are you asking this as a module developer or as a user? Is there a particular module that spams these messages? Past the initial loading I would expect they'd be kept at a minimum.

Would you be happy if I made these messages `console.debug` rather than `console.info`? I don't want to remove them, but setting up a way to toggle logging verbosity that can work before `init` is not exactly simple and I'd prefer to avoid it.

**Comment by dmrickey** [comment]
I didn't consider that the "should I be logging" lookup would have to be done prior to the init hook so that it could be ready in time for the init hook. This question is as a user, I've got a ton of mods loaded and my log is overflowing before I can verify if anything is breaking on startup--so I'm looking for messages that are repeated (even though I understand these are all unique messages) that can be removed.

As a user I don't really care about these messages. I only care about them as a mod dev, but after that point I can just trust that the library is working as expected. Even for the mods I've worked on, though, I've never actually gone in and checked the logs that something was wrapped properly, I just "do the thing" and saw if it worked or not.

**Comment by ruipin** [comment]
Ok, thanks for the detail. I'll think about the options I have, and figure something out.

**Comment by dmrickey** [comment]
If these could all be queued up and logged in a single object/array, I think that would actually be more useful. Especially if they were keyed off of method being wrapped so it's easier to tell if multiple things are wrapping the same method

**Comment by ruipin** [comment]
Implemented in [v1.12.0.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.0.0). By default, the logging verbosity is set to warnings and errors only.
