### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zarhog** [ruipin/fvtt-lib-wrapper#74]
⚠ Most errors triggered by libWrapper are not caused by libWrapper itself, but by a module/package. Do not open a support ticket using this form unless you are seeing an **internal** libWrapper error or are a **package developer** who needs support. We also do not provide support for packages that promote or otherwise endorse piracy. Your issue will be closed as invalid if you do not fulfill these requirements.

The easiest way to find support is to ask the community. The largest community-provided support channels are:
- [FoundryVTT Discord](https://discord.gg/foundryvtt)'s #modules-troubleshooting channel
- [FoundryVTT Reddit](https://www.reddit.com/r/FoundryVTT)

--------------------

**Confirm you have read the above**
After reading the above, very briefly explain why this is the proper channel for your report.

i have used "Find the culprate" and it has determined that your mod is the problem

**Describe the bug**
items are being duplicated when dragged into an inventory

**To Reproduce**
1. Install module librapper
2. Go to item
3. Click on and drag and intom into a new inventory
4. Scroll down to new inventory
5. See error duplicate items

**Expected behavior**
only 1 new item is made in the inventroy not 2

**Screenshots**
[If applicable, add screenshots to help explain your problem.](url)

**Technical Details (please complete the following information):**
 - LibWrapper Version [e.g. `1.6.1.0`, `1.7.2.0`, etc]
 - FoundryVTT Version =  Latest stable update
 <img width="410" alt="image" src="https://user-images.githubusercontent.com/76391362/204445107-a2c036be-d9e3-49ca-a02a-84cc87661255.png">
 - Browser & Version 

 i got lazy as its 5am and hadnt slept
**Additional context**

**Comment by ruipin** [comment]
This is almost certainly not a libWrapper bug, but instead a bug with a module that uses libWrapper.

Find the Culprit thinks it might be libWrapper because disabling it is probably also disabling the real culprit, which depends on libWrapper. You will want to re-run Find The Culprit, and tell it to not consider libWrapper as a possibility.

There is not enough information here (such as the modules list) for me to know what module could be causing the issue. I suspect one that affects the inventory - looking at the logs, this could be for instance "Let's Trade 5e" or "Merchant Sheet NPC".

Regardless, given libWrapper isn't a truly user-facing module, as described at the top of the bug report template I do not offer user-facing support. You'll need to report it as a bug to the module that uses libWrapper, and if they do discover a libWrapper bug, then they'll have the information they need to report it to me.

As such, closing as non-applicable.
